name: CICD
run-name: Build and publish to surge 🚀
on: [push]
jobs:
  Deploy-to-Surge:
    runs-on: ubuntu-latest
    steps:
      - run: npm -v
      - run: ls
      - run: git status
      - run: git branch
